# Copyright (c) 2019-2021 Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
# 

resource "oci_core_instance" "app_instance" {
  availability_domain                 = data.oci_identity_availability_domains.ads.availability_domains[0]["name"]
  compartment_id                      = oci_identity_compartment.app_instance_compartment.id
  display_name                        = "${var.app_tag} App"
  shape                               = var.instance_shape
#  is_pv_encryption_in_transit_enabled = var.is_pv_encryption_in_transit_enabled
  freeform_tags                       = local.common_tags

  source_details {
    source_type = "image"
    source_id   = lookup(data.oci_core_images.compute_images.images[0], "id")
  }

  create_vnic_details {
    subnet_id        = oci_core_subnet.app_instance_subnet_public.id
    display_name     = "${var.app_tag} VNIC"
    assign_public_ip = true
    hostname_label   = "${var.app_tag}"
  }

  metadata = {
    ssh_authorized_keys = var.generate_public_ssh_key ? tls_private_key.compute_ssh_key.public_key_openssh : var.public_ssh_key
    #user_data           = data.template_cloudinit_config.nodes.rendered
  }

  depends_on = [
    oci_core_virtual_network.app_instance_vcn
  ]    
}

### Important Security Notice ###
# The private key generated by this resource will be stored unencrypted in your Terraform state file. 
# Use of this resource for production deployments is not recommended. 
# Instead, generate a private key file outside of Terraform and distribute it securely to the system where Terraform will be run.

# Generate ssh keys to access Compute Nodes, if generate_public_ssh_key=true, applies to the Compute
resource "tls_private_key" "compute_ssh_key" {
  algorithm = "RSA"
  rsa_bits  = 2048
}
