# mysql

mysql_root_password: "{{ admin_password_decrypt.decrypted_data.plaintext | b64decode }}"
mysql_databases:
  - name: phabricator
    encoding: utf8
    collation: utf8_general_ci
mysql_users:
  - name: manager
    host: "%"
    password: "{{ manager_password_decrypt.decrypted_data.plaintext | b64decode }}"
    priv: "phabricator\_%.*:ALL"
mysql_port: 3306
mysql_bind_address: '0.0.0.0'
mysql_daemon: mysqld
mysql_version: 8.0
mysql_default_datadir: "{{ project_directory }}/db"
mysql_packages:
  - mysql-server
  - MySQL-python

# php

php_version: 7.1
php_enablerepo: "remi-php71,epel"
php_memory_limit: "128M"
php_max_execution_time: "90"
php_upload_max_filesize: "256M"

# nginx

nginx_vhosts:
  - listen: "80 default_server"
    server_name: "{{ app_tag }}.{{ user_name }}.fortknox.dev"
    server_name_redirect: "www.{{ app_tag }}.{{ user_name }}.fortknox.dev"
    root: "{{ project_directory }}/fortknox_app/var/www"
    index: "index.php index.html index.htm"
    error_page: ""
    access_log: ""
    error_log: ""
    state: "present"
    template: "{{ nginx_vhost_template }}"
    filename: "{{ app_tag }}.{{ user_name }}.fortknox.dev.conf"
    extra_parameters: |
      location ~ \.php$ {
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass unix:/var/run/php5-fpm.sock;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          include fastcgi_params;
      }
  - listen: "443 ssl http2"
    server_name: "{{ app_tag }}.{{ user_name }}.fortknox.dev"
    server_name_redirect: "www.{{ app_tag }}.{{ user_name }}.fortknox.dev"
    root: "{{ project_directory }}/fortknox_app/var/www"
    index: "index.php index.html index.htm"
    error_page: ""
    access_log: ""
    error_log: ""
    state: "present"
    template: "{{ nginx_vhost_template }}"
    filename: "{{ app_tag }}.{{ user_name }}.fortknox.dev.conf"
    extra_parameters: |
      location ~ \.php$ {
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass unix:/var/run/php5-fpm.sock;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          include fastcgi_params;
      }
