# mysql

mysql_root_password: "{{ admin_password_decrypt.decrypted_data.plaintext | b64decode }}"
mysql_databases:
  - name: phabricator
    encoding: utf8
    collation: utf8_general_ci
mysql_users:
  - name: manager
    host: "%"
    password: "{{ manager_password_decrypt.decrypted_data.plaintext | b64decode }}"
    priv: "phabricator\_%.*:ALL"
mysql_port: 3306
mysql_bind_address: '0.0.0.0'
mysql_daemon: mysqld
mysql_version: 8.0
mysql_relocate_datadir: "{{ project_directory }}/db"
mysql_packages:
  - mysql-server
  - MySQL-python

# php

php_version: 7.1
php_enablerepo: "remi-php71,epel"

php_fpm_pool_user: "www-user"
php_fpm_pool_group: "fortknox"
php_memory_limit: "256M"
php_max_execution_time: "90"
php_max_input_time: "60"
php_max_input_vars: "1000"
php_realpath_cache_size: "32K"
php_file_uploads: "On"
php_upload_max_filesize: "256M"
php_max_file_uploads: "20"
php_post_max_size: "32M"
php_date_timezone: "America/Chicago"
php_allow_url_fopen: "On"
php_sendmail_path: "/usr/sbin/sendmail -t -i"
php_output_buffering: "4096"
php_short_open_tag: false
php_error_reporting: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
php_display_errors: "Off"
php_display_startup_errors: "On"
php_expose_php: "On"
php_session_cookie_lifetime: 0
php_session_gc_probability: 1
php_session_gc_divisor: 1000
php_session_gc_maxlifetime: 1440
php_session_save_handler: files
php_session_save_path: ''
php_disable_functions: []
php_precision: 14
php_serialize_precision: "-1"

# nginx

nginx_vhosts:
  - listen: "80 default_server"
    server_name: "{{ app_tag }}.{{ user_name }}.fortknox.dev"
    server_name_redirect: "www.{{ app_tag }}.{{ user_name }}.fortknox.dev"
    root: "{{ project_directory }}/fortknox_app/var/www"
    index: "index.php index.html index.htm"
    error_page: ""
    access_log: ""
    error_log: ""
    state: "present"
    template: "{{ nginx_vhost_template }}"
    filename: "{{ app_tag }}.{{ user_name }}.fortknox.dev.conf"
    extra_parameters: |
      location ~ \.php$ {
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass unix:/var/run/php5-fpm.sock;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          include fastcgi_params;
      }
  - listen: "443 ssl http2"
    server_name: "{{ app_tag }}.{{ user_name }}.fortknox.dev"
    server_name_redirect: "www.{{ app_tag }}.{{ user_name }}.fortknox.dev"
    root: "{{ project_directory }}/fortknox_app/var/www"
    index: "index.php index.html index.htm"
    error_page: ""
    access_log: ""
    error_log: ""
    state: "present"
    template: "{{ nginx_vhost_template }}"
    filename: "{{ app_tag }}.{{ user_name }}.fortknox.dev.conf"
    extra_parameters: |
      location ~ \.php$ {
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass unix:/var/run/php5-fpm.sock;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          include fastcgi_params;
      }

# phabricator

phabricator_web_user: "www-user"
phabricator_web_group: "fortknox"
