---
- name: Git checkout arcanist
  ansible.builtin.git:
    repo: https://github.com/inkton/arcanist.git
    dest: "{{ project_directory }}/fortknox_app/bin/arcanist"
    accept_hostkey: true

- name: Git checkout phabricator
  ansible.builtin.git:
    repo: https://github.com/inkton/phabricator.git
    dest: "{{ project_directory }}/fortknox_app/var/www/phabricator"

