---
# role: ansible-role-phabricator
# file: tasks/main.yml

- name: "Tasks for ansible-role-phabricator"
  block:

    - name: "Set os_family dependent variables"
      include_vars: '{{ ansible_os_family }}.yml'

    - name: "Set distribution dependent variables"
      include_vars: "{{ item }}"
      vars:
        params:
          files:
            - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
            - '{{ ansible_distribution }}.yml'
            - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
          paths:
            - 'vars'
          skip: true
      loop: "{{ query('first_found', params, errors='ignore') }}"

    - name: "Install packages for ansible-role-phabricator"
      package:
        name: "{{ phabricator_packages }}"
        state: present

# Setup and configure.
    - include_tasks: configure.yml
  when: phabricator_role_enabled | bool
